apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-db
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
